openapi: "3.0.0"
info:
  version: 1.0.0
  title: AmericanFflightsComponents to remote
paths: {}

components: 
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header

  examples:
    flight:
      value: 
        ID: 234
        code: ER38sd
        price: 400
        departureDate: 2017/07/26
        origin: CLE
        destination: SFO
        emptySeats: 0
        plane:
          type: Boeing 737
          totalSeats: 150
    flightNoID:
      value: 
        code: ER34sg
        price: 500
        departureDate: 2017/07/26
        origin: CLE
        destination: SFO
        emptySeats: 0
        plane:
          type: Boeing 737
          totalSeats: 150
    flightsList:
      value: 
        - 
          ID: 1
          code: ER66pl
          price: 400
          departureDate: 2017/07/24
          origin: EZE
          destination: MIA
          emptySeats: 0
          plane:
            type: Boeing 737
            totalSeats: 150
        -
          ID: 123
          code: ADE23
          price: 490
          departureDate: 2017/07/24
          origin: NYC
          destination: SFO
          emptySeats: 3
          plane:
            type: Boeing 737
            totalSeats: 150
  schemas:
    AmericanFlightDataType:
      type: object
      description: American Flight Data Type
      properties:
        ID?: 
          type: number
        code:  
          type: string
        price:  
          type: number
        departureDate:  
          type: string
        origin:  
          type: string
        destination:  
          type: string
        emptySeats:  
          type: number
        plane:
          type: object
          properties: 
            type:  
              type: string
            totalSeats:  
              type: number